### ISSUE TITLE
Folder structure - too many main_frame_project 

### ISSUE THREAD

**Issue by kevinortiz43** [JaroslawPogoda/main_frame#5]
I want to remove main_frame_project, currently there are 3. 

![image](https://github.com/user-attachments/assets/3f392a08-56d3-46e3-a4b0-d917dd314dd4)

**Comment by JaroslawPogoda** [comment]
![image](https://github.com/user-attachments/assets/d4cdfb9d-b7cd-4fca-b94a-a62da434f36c)
fixed repetitive naming convention

**Comment by JaroslawPogoda** [comment]
fixed
